package shadow.lsp;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Collections;
import java.util.List;
import org.apache.logging.log4j.LogManager;
import shadow.ConfigurationException;
import shadow.ShadowException;
import shadow.typecheck.ErrorReporter;
import shadow.typecheck.TypeChecker;

// Wraps the Shadow compiler's type-checker for use by the LSP.
// NOTE: Configuration.buildConfiguration(...) must be called once elsewhere
// (server startup / test setup) before check() will work — TypeChecker
// depends on that static global state.
public class Compiler {

  // NOTE: warnings will always be empty for now. Compiler warnings (unused
  // field/method) are only generated by optimizeTAC() in shadow.Main, which
  // typeCheck() alone never calls. Wiring that in is future work.
  public static final class CheckResult {
    public final List<ShadowException> errors;
    public final List<ShadowException> warnings;

    public CheckResult(List<ShadowException> errors, List<ShadowException> warnings) {
      this.errors = Collections.unmodifiableList(errors);
      this.warnings = Collections.unmodifiableList(warnings);
    }
  }

  // Only call this with a file that's actually saved to disk (didOpen/didSave).
  // typeCheck() has no in-memory-source entry point.
  public CheckResult check(Path file) throws IOException, ConfigurationException {
    // Must be absolute/normalized — Configuration's import map uses absolute
    // paths as keys, so a relative path here fails to resolve.
    file = file.toAbsolutePath().normalize();

    if (!Files.exists(file)) {
      return new CheckResult(List.of(), List.of());
    }

    ErrorReporter reporter = new ErrorReporter(LogManager.getLogger(Compiler.class));

    List<Path> files = List.of(file);

    try {
      TypeChecker.typeCheck(files, reporter, true);
    } catch (ShadowException e) {
      // A ShadowException here means "the code has an error" (expected
      // outcome), not "checking failed" — so it's captured as data, not
      // rethrown. IOException/ConfigurationException are real failures and
      // propagate normally.
      reporter.addError(e);
    }

    // TODO: same logical error can appear more than once in this list
    // (seen: one undeclared-variable reference reported twice, likely from
    // outer/inner class node revisiting in TypeChecker). Check whether
    // ErrorReporter.removeRedundantErrors() handles this, or add dedup here,
    // before this list becomes LSP Diagnostics.
    return new CheckResult(reporter.getErrorList(), reporter.getWarningList());
  }
}
